name: ${project.name}
main: de.themoep.commandblockpermissions.CommandBlockPermissions
version: '${minecraft.plugin.version}'
description: ${project.description}
authors: [Phoenix616]
depend: [ProtocolLib]
commands:
   commandblockpermissions:
      aliases: [cbp, commandblockperms, cbperms]
      description: Main plugin command
      usage: /<command> [reload|disabled <player> <command...>]
      permission: cbp.command
      permission-message: You don't have the permission <permission>
permissions:
   cbp.receivewarnings:
      description: Gives permission to receive warnings
      default: false
   cbp.commandblock.place:
      description: Gives permission to place command blocks
      default: false
   cbp.commandblock.break:
      description: Gives permission to break command blocks
      default: false
   cbp.commandblock.access:
      description: Gives permission to access command blocks
      default: false
   cbp.commandblock.change:
      description: Gives permission to change command blocks
      default: false
   cbp.command:
      description: Gives permission to the plugin command
      default: false
   cbp.command.reload:
      description: Gives permission to reload the plugin
      default: false
   cbp.options.disabletrackoutput:
      description: Gives permission to disable tracking of output
      default: false
   cbp.options.conditional:
      description: Gives permission to set command blocks to conditional mode
      default: false
   cbp.options.mode.redstone:
      description: Gives permission to use the redstone mode
      default: true
   cbp.options.mode.auto:
      description: Gives permission to use the automatic mode
      default: false
   cbp.options.mode.sequence:
      description: Gives permission to use the sequence mode
      default: false